cd solvers/flaresolver01; export PUPPETEER_PRODUCT=firefox; npm install; screen -AmdS solver1 npm run
cd ../; cd flaresolver02; export PUPPETEER_PRODUCT=firefox; npm install; screen -AmdS solver2 npm run
cd ../; cd flaresolver03; export PUPPETEER_PRODUCT=firefox; npm install; screen -AmdS solver3 npm run
cd ../; cd flaresolver04; export PUPPETEER_PRODUCT=firefox; npm install; screen -AmdS solver4 npm run
cd ../; cd flaresolver05; export PUPPETEER_PRODUCT=firefox; npm install; screen -AmdS solver5 npm run
cd ../; cd flaresolver06; export PUPPETEER_PRODUCT=firefox; npm install; screen -AmdS solver6 npm run
cd ../; cd flaresolver07; export PUPPETEER_PRODUCT=firefox; npm install; screen -AmdS solver7 npm run
cd ../; cd flaresolver08; export PUPPETEER_PRODUCT=firefox; npm install; screen -AmdS solver8 npm run
cd ../; cd flaresolver09; export PUPPETEER_PRODUCT=firefox; npm install; screen -AmdS solver9 npm run
cd ../; cd flaresolver10; export PUPPETEER_PRODUCT=firefox; npm install; screen -AmdS solver10 npm run