cd solvers/flaresolver01; export PUPPETEER_PRODUCT=firefox; npm install; screen -AmdS solver1 npm start
cd ../; cd flaresolver02; export PUPPETEER_PRODUCT=firefox; npm install; screen -AmdS solver2 npm start
cd ../; cd flaresolver03; export PUPPETEER_PRODUCT=firefox; npm install; screen -AmdS solver3 npm start
cd ../; cd flaresolver04; export PUPPETEER_PRODUCT=firefox; npm install; screen -AmdS solver4 npm start
cd ../; cd flaresolver05; export PUPPETEER_PRODUCT=firefox; npm install; screen -AmdS solver5 npm start
cd ../; cd flaresolver06; export PUPPETEER_PRODUCT=firefox; npm install; screen -AmdS solver6 npm start
cd ../; cd flaresolver07; export PUPPETEER_PRODUCT=firefox; npm install; screen -AmdS solver7 npm start
cd ../; cd flaresolver08; export PUPPETEER_PRODUCT=firefox; npm install; screen -AmdS solver8 npm start
cd ../; cd flaresolver09; export PUPPETEER_PRODUCT=firefox; npm install; screen -AmdS solver9 npm start
cd ../; cd flaresolver10; export PUPPETEER_PRODUCT=firefox; npm install; screen -AmdS solver10 npm start
